[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM3
;  monitor_filters = debug, send_on_enter
monitor_filters = send_on_enter, default
monitor_echo = yes
monitor_encoding = UTF-8
lib_deps = 
    madhephaestus/ESP32Encoder @ ^0.10.1